version: '3'

services:
  calculator-api:
    image: tiangolo/uvicorn-gunicorn-fastapi:python3.9
    ports:
      - "8000:8000"
    networks:
      - mysql-network
    depends_on:
      - database
    volumes:
      - ./:/app
    command: sh -c "sleep 10; pip install -r requirements.txt && uvicorn main:app --host 0.0.0.0 --port 8000"

  database:
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
    networks:
      - mysql-network
    volumes:
      - ./mysql.cnf:/etc/mysql/conf.d/mysql.cnf

networks:
  mysql-network:
    driver: bridge
